server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: product-search-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

application:
  external:
    api:
      bestBuyProductUrl: "https://www.bestbuy.ca/api/v2/json/search?categoryid=%s&lang=en-CA&page=%s&pageSize=%s&path=&query=%s"
      bestBuyLocationUrl: "https://stores.bestbuy.ca/en-ca/search?q=%s"
      bestBuyInventoryUrl: "https://www.bestbuy.ca/ecomm-api/availability/products?accept=application%2Fvnd.bestbuy.standardproduct.v1%2Bjson&accept-language=en-CAl&ocations={0}&skus={1}"
