server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: authentication-server-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false