server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: authentication-server-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
      uri: mongodb+srv://auth-server:ki6bn3QrQVbAbPph@cluster0.6xdtq.mongodb.net/nolis
      database: nolis

## Application Configuration Properties
application:
  jwt:
    secretKey: 12345678901234567890123456789012
    tokenExpirationAfterDays: 1
    refreshTokenExpirationAfterDays: 30
    tokenPrefix: "Bearer "
    accessHeader: access_token
    refreshHeader: refresh_token
    issuer: nolis
    audience: nolis
  service:
    redis:
      host: "localhost"
      port: 6380
      cache:
        - name: "AppUsers"
          ttl: 20
          unit: SECONDS
        - name: "AppRoles"
          ttl: 20
          unit: SECONDS





