eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-search-service
          uri: "lb://product-search-service"
          predicates:
            Path=/api/v1/products/**
          filters:
            - AuthRedirectFilter
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            Path=/eureka/web
          filters:
            SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            Path=/eureka/**
        - id: authentication-server-service
          uri: "lb://authentication-server-service"
          predicates:
            Path=/api/v1/auth/**
        - id: authentication-server-service-login
          uri: "lb://authentication-server-service"
          predicates:
            Path=/api/v1/auth/login/**
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

server:
  port: 8080
## Logging path for the gateway service
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          cloud:
          gateway.route.RouteDefinitionLocator: INFO
          gateway: TRACE


