eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-search-service
          uri: "lb://product-search-service"
          predicates:
            Path=/api/v1/products/**
          filters:
            - AuthRedirectFilter
      routes[1]:
        id: eureka-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[2]:
        id: eureka-server-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
      routes[3]:
        id: authentication-server-service
        uri: "lb://authentication-server-service"
        predicates[0]: Path=/api/v1/auth/**
      routes[4]:
        id: authentication-server-service-login
        uri: "lb://authentication-server-service"
        predicates[0]: Path=/api/v1/auth/login/**
    loadbalancer:
      ribbon:
        enabled: false

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

server:
  port: 8080
## Logging path for the gateway service
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          cloud:
          gateway.route.RouteDefinitionLocator: INFO
          gateway: TRACE


